# Utilisez une image Node.js comme base
FROM node:14

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers package.json et package-lock.json
COPY package*.json ./

# Installez les dépendances de l'application
RUN npm install

# Copiez tous les fichiers du projet dans le conteneur
COPY . .

# Exécuter les scripts
CMD ["sh", "entrypoint.sh"]
